language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.14"
  - "5.10"
before_install:
  - find /home/travis/perl5 -name Critic\*
  - cpanm --quiet --installdeps --notest Test::Perl::Critic
  - find /home/travis/perl5 -name Critic\*
  - cd Brocade-BSC
script:
  - perl Makefile.PL && make test && prove -l xt
  - find /home/travis/perl5 -name Critic\*

