language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.14"
  - "5.10"
before_install:
  - if [ $(perl -e 'print $^V' | cut -d'.' -f2) -ge 20 ] ; then cpanm --quiet --installdeps --notest Test::Perl::Critic ; cpanm --quiet --notest Test::Perl::Critic ; fi
  - cd Brocade-BSC
script:
  - perl Makefile.PL && make test && prove -l xt
