language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.14"
  - "5.10"
before_install:
  - cpanm --quiet --installdeps --notest Test::Perl::Critic
  - cd Brocade-BSC
script:
  - perl Makefile.PL && make test && prove -l xt
